package com.testing123.ui;

import com.testing123.vaadin.FlotOptions;
import com.testing123.vaadin.Graph;
import com.testing123.vaadin.Retriever;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;

@SuppressWarnings("serial")
public class MainComponent extends CustomComponent {
	private static final String PANEL_WIDTH = "1000px";
	private static final String PANEL_HEIGHT = "500px";
	private static final String GRAPH_WIDTH = "800px";
	private static final String GRAPH_HEIGHT = "400px";

	private AbsoluteLayout mainLayout;
	private AbsoluteLayout absoluteLayout_2;
	private String startDate;
	private String endDate;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainComponent(String startDate, String endDate) {
		this.startDate = startDate;
		this.endDate = endDate;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth(PANEL_WIDTH);
		mainLayout.setHeight(PANEL_HEIGHT);
		
		// top-level component properties
		setWidth(PANEL_WIDTH);
		setHeight(PANEL_HEIGHT);
		
		// Graph
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2);

		
		return mainLayout;
	}

	@AutoGenerated
	public AbsoluteLayout buildAbsoluteLayout_2() {		
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth(PANEL_WIDTH);
		absoluteLayout_2.setHeight(PANEL_HEIGHT);
		
		Label graphName = new Label("<b>Platform Project</b>", ContentMode.HTML);
		graphName.setStyleName("h2");
		absoluteLayout_2.addComponent(graphName);
		Label dateRange = new Label(startDate + " to " + endDate);
		dateRange.setStyleName("p");
		absoluteLayout_2.addComponent(dateRange, "top: 20px;");
		
		Graph chart = new Graph();
		chart.setWidth(GRAPH_WIDTH);
		chart.setHeight(GRAPH_HEIGHT);

		chart.setData("[" + Retriever.getData(startDate, endDate) + "]");

		chart.setOptions(FlotOptions.getString());
		
		absoluteLayout_2.addComponent(chart, "top: 50px;");
		return absoluteLayout_2;
	}
}