package com.testing123.ui;

import javax.servlet.annotation.WebServlet;

import com.testing123.controller.ParameterManager;
import com.testing123.controller.UIState;
import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.Title;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.DeploymentConfiguration;
import com.vaadin.server.ServiceException;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinResponse;
import com.vaadin.server.VaadinServlet;
import com.vaadin.server.VaadinSession;
import com.vaadin.server.VaadinServletService;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

/**
 * QicUI acts as the "Main" of the program.  It sets up the server and initializes the layout for
 * the user interface.
 * 
 * @author chenc
 *
 */
@Push(PushMode.MANUAL)
@SuppressWarnings("serial")
@Theme("mytheme")
@Title("Quality Induced Constraints")
public class QicUI extends UI {
	public static final String LEFT_MARGIN_WIDTH = "100px";
	public static final String FIRST_ROW_HEIGHT = "90px";
	
	public static final String COMPONENT_WIDTH = "1000px";
	public static final String COMPONENT_HEIGHT = "550px";
	public static final String GRAPH_WIDTH = "1000px";
	public static final String GRAPH_HEIGHT = "500px";
	
	/**
	 * Required to run the server (autogenerated by the framework)
	 * 
	 * @author chenc
	 */
	@WebServlet(value = "/*", asyncSupported = true)
	@VaadinServletConfiguration(productionMode = false, ui = QicUI.class)
	public static class Servlet extends VaadinServlet {

		/**
		 * Included for threading
		 */
	    @Override
	    protected VaadinServletService createServletService(DeploymentConfiguration deploymentConfiguration) throws ServiceException {
	        VaadinServletService servletService = new VaadinServletService(this, deploymentConfiguration) {
	            
	        	@Override
	            public void requestStart(VaadinRequest request, VaadinResponse response) {
	                super.requestStart(request, response);
	            }

	            @Override
	            public void requestEnd(VaadinRequest request, VaadinResponse response, VaadinSession session) {
	                super.requestEnd(request, response, session);
	            }
	        };
	        servletService.init();
	        return servletService;
	    }
	}

	
	/**
	 * Initializes the server with a new request.  Sets the layout of the page.  Current layout below:
	 * 		V1
	 * 	(H1 H2 H3) as V2
	 * 		V3
	 * 
	 * @param request
	 */
	@Override
	protected void init(VaadinRequest request) {
		//final GridLayout layout = new GridLayout(3, 4);
		
	    final VerticalLayout mainVerticalLayout = new VerticalLayout();
		mainVerticalLayout.setMargin(false);
		setContent(mainVerticalLayout);
		
//		final AbsoluteLayout l1 = new AbsoluteLayout();
//		l1.setWidth(LEFT_MARGIN_WIDTH);
//		l1.setHeight(FIRST_ROW_HEIGHT);
//		l1.setStyleName("header_background");
		
		final AbsoluteLayout headingText = new AbsoluteLayout();
		headingText.setWidth("100%");
		headingText.setHeight(FIRST_ROW_HEIGHT);
		
		UIState state = new ParameterManager().getState(request.getParameter("st"), request.getParameter("end"),
				request.getParameter("x"), request.getParameter("y"), request.getParameter("proj"), 
				request.getParameter("auth"));
		
		Label title = new Label("Quality Induced Constraints", ContentMode.HTML);
		title.setStyleName("b");
		title.setStyleName("h1");
		//title.setStyleName("header_background");
		headingText.addComponent(title);
		headingText.setStyleName("header_background");
		mainVerticalLayout.addComponent(headingText);
		
		NavigationComponent nav = new NavigationComponent(mainVerticalLayout, state);
		mainVerticalLayout.addComponent(nav);
	}
}